spatial_dims: 2
in_channels: 1 
out_channels: 1
num_channels: 
    - 128
    - 256
    - 256
attention_levels:
    - False
    - True
    - True
num_res_blocks: 1
num_head_channels: 256

# Scheduling and noising scheme
train_scheduler: "ddpm"
inference_scheduler: "ddpm"
inference_steps: 1000
noise_level: 300
noise_type: "gaussian"
prediction_type: "epsilon"
